SELECT * FROM KSFPA.MR2C.RECEIPT_DETAIL_WORK
WHERE ORDER_GENERATED_IDENTIFIER = 1859901000015//1859901000015//1817704300015
AND PRODUCT_GENERATED_IDENTIFIER = 4289812200004//4289812200004//4303730800004

SELECT * FROM KSFPA.MR2C.OS_CHARGE_DETAIL
WHERE ORDER_GENERATED_IDENTIFIER = 1859901000015//1859901000015//1817704300015
AND PRODUCT_GENERATED_IDENTIFIER = 4289812200004//4289812200004//4303730800004

SELECT * FROM KSFPA.MR2C.OS_RECEIPT_DETAIL
WHERE ORDER_GENERATED_IDENTIFIER = 1859901000015//1859901000015//1817704300015
AND PRODUCT_GENERATED_IDENTIFIER = 4289812200004//4289812200004//4303730800004


SELECT ORDER_GENERATED_IDENTIFIER, ITEM_GENERATED_IDENTIFIER, SUM(OS_RECEIPT_VAR_QUANTITY) AS VAR_QTY,
COUNT(*) AS OCC, MAX(RECON_WEEK_END_DATE) AS MAX_RECON_WEEK_END_DATE, MIN(RECON_WEEK_END_DATE) AS MIN_RECON_WEEK_END_DATE,
MAX(RECON_WEEK_END_DATE) - MIN(RECON_WEEK_END_DATE) AS DAYS
FROM KSFPA.MR2C.DC_CHARGE_RECONCILIATION
WHERE OS_RECEIPT_VAR_QUANTITY <> 0
GROUP BY 1,2
--ORDER BY OCC DESC
HAVING ABS(VAR_QTY) = 0
--AND MAX_RECON_WEEK_END_DATE >= '2022-07-01'
AND DAYS >= 180
AND OCC = 0


SELECT * FROM KSFPA.MR2C.DC_CHARGE_RECONCILIATION
WHERE ORDER_GENERATED_IDENTIFIER = 1859901000015//1859901000015//1817704300015
AND ITEM_GENERATED_IDENTIFIER = 4289812200004//4289812200004//4303730800004

------------------------------------
;
SELECT * 
FROM KSFPA.MR2C.RECEIPT_DETAIL_WORK

;


WITH

CHARGE AS
(
SELECT 
	PRODUCT_GENERATED_IDENTIFIER ,
	LOCATION_GENERATED_IDENTIFIER ,
	ORDER_GENERATED_IDENTIFIER ,
	SUPPLIER_GENERATED_IDENTIFIER ,
	CONTAINER_GENERATED_IDENTIFIER ,
	
	RECON_WEEK_END_DATE ,
	CURRENT_EFFECTIVE_DATE ,
	TF_UNPACK_SENT_DATE ,
	ACTUAL_UNPACK_DATE ,
	
	CONTAINER_ITEM_LINE_NUMBER ,
	FCR_NUMBER ,
	FLOW_CHANNEL ,
	BRAND_COST ,
	SUB_BRAND ,
	OS_CHARGE_COST_AMT ,
	OS_CHARGE_QTY ,
	SUPPLIER_COST 
	
FROM KSFPA.MR2C.OS_CHARGE_DETAIL
)
,

RECEIPT AS
(
SELECT 
	PRODUCT_GENERATED_IDENTIFIER ,
	LOCATION_GENERATED_IDENTIFIER ,
	ORDER_GENERATED_IDENTIFIER ,
	SUPPLIER_GENERATED_IDENTIFIER ,
	RECEIPT_GENERATED_IDENTIFIER ,
	
	RECON_WEEK_END_DATE ,
	OS_RECEIPT_DATE ,
	CURRENT_EFFECTIVE_DATE ,
	OS_RECEIPT_PROCESS_DATE_MF ,
	
	OC_RECEIPT_UNIT_COST ,
	OS_RECEIPT_QUANTITY ,
	OS_RECEIPT_COST_AMT 
	
FROM KSFPA.MR2C.OS_RECEIPT_DETAIL
)
,
MERGED_VIEW AS
(
SELECT * 
FROM 
	CHARGE
FULL OUTER JOIN 
	RECEIPT
ON
	CHARGE.PRODUCT_GENERATED_IDENTIFIER  = RECEIPT.PRODUCT_GENERATED_IDENTIFIER 	AND
	CHARGE.LOCATION_GENERATED_IDENTIFIER  = RECEIPT.LOCATION_GENERATED_IDENTIFIER 	AND
	CHARGE.ORDER_GENERATED_IDENTIFIER  = RECEIPT.ORDER_GENERATED_IDENTIFIER 		AND
	CHARGE.SUPPLIER_GENERATED_IDENTIFIER  = RECEIPT.SUPPLIER_GENERATED_IDENTIFIER 	
)


-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

SELECT * FROM MERGED_VIEW
--SELECT * FROM RECEIPT
--SELECT * FROM CHARGE

-------------------------------------------------------------------------------

--SELECT COUNT(*) FROM MERGED_VIEW
--SELECT COUNT(*) FROM RECEIPT
--SELECT COUNT(*) FROM CHARGE

-------------------------------------------------------------------------------

--SELECT *
--FROM CHARGE
--WHERE 	
--	PRODUCT_GENERATED_IDENTIFIER ||	
--	LOCATION_GENERATED_IDENTIFIER ||
--	ORDER_GENERATED_IDENTIFIER ||
--	SUPPLIER_GENERATED_IDENTIFIER ||
--	CONTAINER_GENERATED_IDENTIFIER 
--	IN 
--	(
--		SELECT 
--			PRODUCT_GENERATED_IDENTIFIER ||	
--			LOCATION_GENERATED_IDENTIFIER ||
--			ORDER_GENERATED_IDENTIFIER ||
--			SUPPLIER_GENERATED_IDENTIFIER ||
--			CONTAINER_GENERATED_IDENTIFIER 
----			,
----			COUNT(*) 
--		FROM CHARGE
--		GROUP BY 1
--		HAVING COUNT(*) > 1
--	)
--ORDER BY 1,2,3,4,5

-------------------------------------------------------------------------------

--SELECT 
--	PRODUCT_GENERATED_IDENTIFIER ||	
--	LOCATION_GENERATED_IDENTIFIER ||
--	ORDER_GENERATED_IDENTIFIER ||
--	SUPPLIER_GENERATED_IDENTIFIER ||
--	RECEIPT_GENERATED_IDENTIFIER 
--	, COUNT(*) 
--FROM RECEIPT
--GROUP BY 1
--HAVING COUNT(*) > 1

-------------------------------------------------------------------------------
