-- This query will give you information at PO-DC-product level



SELECT * FROM 
KSF_DATAANALYTICS_DEV.DS_SHRINK.DC_PROD_RECON_WEEK_CHARGE_RECEIPT_VARIANCE
KSF_DATAANALYTICS_DEV.DS_SHRINK.DC_PROD_RECON_WEEK_CHARGE_VARIANCE

WHERE ORDER_GENERATED_IDENTIFIER = 1832180100015
AND PRODUCT_GENERATED_IDENTIFIER = 4297383600004




