create or replace view KSF_DATAANALYTICS_DEV.DS_SHRINK.DUPLICATED_RECEIPT_IPS(
  LOCATION_GENERATED_IDENTIFIER,
  DAY_DATE,
  PRODUCT_GENERATED_IDENTIFIER,
  STOCK_MOVEMENT_REFERENCE_ID,
  TOTAL_QTY_ADJ,
  MAX_QTY_ADJ,
  NUMBER_OF_ADJ
) as
select LOCATION_GENERATED_IDENTIFIER, DAY_DATE, PRODUCT_GENERATED_IDENTIFIER, STOCK_MOVEMENT_REFERENCE_ID, 
sum(STOCK_MOVEMENT_QUANTITY) as total_qty_adj,
max(STOCK_MOVEMENT_QUANTITY) as max_qty_adj,
count(*) as number_of_adj
from KSFPA.IPS_STOCK_AUDIT.IPS_STOCK_AUDIT
where STOCK_MOVEMENT_SOURCE IN ('ERD_SRS')
and DAY_DATE >= '2023-02-01'
group by LOCATION_GENERATED_IDENTIFIER, DAY_DATE, PRODUCT_GENERATED_IDENTIFIER, STOCK_MOVEMENT_REFERENCE_ID
having number_of_adj > 1
and total_qty_adj <> max_qty_adj
and (total_qty_adj/number_of_adj) = max_qty_adj;


-----------------------------------------------------------------------------------------------------------------------------

create or replace view KSFPA.LOSS_PREVENTION_PVT.DUPLICATED_STK_ADJ_VD(
  KEYCODE,
  PRODUCT_DESCRIPTION,
  DEPARTMENT_DESCRIPTION,
  STORE,
  LOCATION_NAME,
  STATE,
  DC_GROUP_ABBREV_NAME,
  TRANSACTION_USER_ID,
  DAY_DATE,
  STOCK_MOVEMENT_CODE,
  STOCK_MOVEMENT_QUANTITY,
  FREQUENCY,
  TOTAL_STOCK_MOVEMENT_QUANTITY
) as
select B.PRODUCT_SOURCE_IDENTIFIER as KEYCODE, B.PRODUCT_DESCRIPTION, B.DEPARTMENT_DESCRIPTION,
C.LOCATION_SOURCE_IDENTIFIER as STORE, C.LOCATION_NAME, C.STATE, C.DC_GROUP_ABBREV_NAME,
a.TRANSACTION_USER_ID, a.DAY_DATE, a.STOCK_MOVEMENT_CODE, a.STOCK_MOVEMENT_QUANTITY,
count(*) as FREQUENCY, sum(a.STOCK_MOVEMENT_QUANTITY) as TOTAL_STOCK_MOVEMENT_QUANTITY
from KSFPA.IPS_STOCK_AUDIT.IPS_STOCK_AUDIT A
inner join KSFPA.MR2C.KEYCODE B
on A.PRODUCT_GENERATED_IDENTIFIER = B.PRODUCT_SOURCE_IDENTIFIER
inner join KSFPA.MR2C.LOCATION C
on A.LOCATION_GENERATED_IDENTIFIER = C.LOCATION_SOURCE_IDENTIFIER
where A.DAY_DATE >= '2023-02-01'
and A.STOCK_MOVEMENT_SOURCE ='Shrinkage'
and A.STOCK_MOVEMENT_QUANTITY <> 0
--and A.STOCK_MOVEMENT_CODE = '20'
--and C.LOCATION_SOURCE_IDENTIFIER = 1025
group by 1,2,3,4,5,6,7,8,9,10,11
having FREQUENCY >1;