
SELECT * FROM KSF_DATAANALYTICS_DEV.DS_SHRINK.DC_CHARGE_VARIANCE_CONTAINER ;

SELECT * FROM KSF_DATAANALYTICS_DEV.DS_SHRINK.DC_CHARGE_VARIANCE_RECEIPT ;

-----------------------------------------------------

CREATE OR REPLACE TABLE KSF_DATAANALYTICS_DEV.DS_SHRINK.DC_CHARGE_VARIANCE_REPORT_ONE_TIME_LOAD AS
SELECT * FROM KSF_SOPHIA_DATA_INTELLIGENCE_HUB_DEV.SHRINK_TACTICAL.DC_CHARGE_VARIANCE ;

SELECT * FROM KSF_DATAANALYTICS_DEV.DS_SHRINK.DC_CHARGE_VARIANCE_REPORT_ONE_TIME_LOAD ;

-----------------------------------------------------

CREATE OR REPLACE TABLE KSF_DATAANALYTICS_DEV.DS_SHRINK.DC_CHARGE_VARIANCE_RECON AS
SELECT * FROM KSFPA.MR2C.DC_CHARGE_RECONCILIATION ;

SELECT * FROM KSF_DATAANALYTICS_DEV.DS_SHRINK.DC_CHARGE_VARIANCE_RECON ;

-----------------------------------------------------

CREATE OR REPLACE TABLE KSF_DATAANALYTICS_DEV.DS_SHRINK.DC_RECON_CODE_MSG_MAP AS
SELECT * FROM KSFPA.MR2C.DC_CHARGE_RECONCILIATION_STATUS ;

SELECT * FROM KSF_DATAANALYTICS_DEV.DS_SHRINK.DC_RECON_CODE_MSG_MAP ;

-----------------------------------------------------

CREATE OR REPLACE TABLE KSF_DATAANALYTICS_DEV.DS_SHRINK.DC_CHARGE_VARIANCE_CONTAINER_T AS
SELECT * FROM KSFPA.MR2C.OS_CHARGE_DETAIL ;

SELECT * FROM KSF_DATAANALYTICS_DEV.DS_SHRINK.DC_CHARGE_VARIANCE_CONTAINER_T ;

-----------------------------------------------------

CREATE OR REPLACE TABLE KSF_DATAANALYTICS_DEV.DS_SHRINK.DC_CHARGE_VARIANCE_RECEIPT_T AS
SELECT * FROM KSFPA.MR2C.OS_RECEIPT_DETAIL ;

SELECT * FROM KSF_DATAANALYTICS_DEV.DS_SHRINK.DC_CHARGE_VARIANCE_RECEIPT_T ;


