-----------For Instore----------------
SELECT 
REFUND_TABLE.DEPARTMENT AS DEPARTMENT,
REFUND_TABLE.DEPARTMENT_DES as DEPARTMENT_DES,
REFUND_TABLE.CLASS as CLASS,
REFUND_TABLE.CLASS_DES as CLASS_DES,
--COALESCE(
COALESCE(TRIM(REFUND_TABLE.REASON_DESCRIPTION),'NONE')AS REASON_DESCRIPTION,
SUM(IFNULL(REFUND_TABLE.refund_price,0) )AS refund_price
--SUM(Sales.SALES_TRN_ID_COUNT) AS SALES_TRN_ID_COUNT,
--SUM(IFNULL(SALES_TABLE.sales_price,0)) AS sales_price
--SUM (REFUND_TABLE.Refund )AS REFUND_TRN_ID_COUNT,
--SUM(REFUND_TABLE.refund_price) AS refund_price ,
--SUM(SALES_TABLE.Sales) AS SALES_TRN_ID_COUNT,
--SUM(SALES_TABLE.sales_price)AS sales_price
FROM 
(
SELECT Ref_table.M_STORE,
  keycode.DEPARTMENT_SOURCE_IDENTIFIER AS DEPARTMENT,
   keycode.CLASS_SOURCE_IDENTIFIER AS CLASS,
  keycode.DEPARTMENT_DESCRIPTION AS DEPARTMENT_DES, 
   keycode.CLASS_DESCRIPTION AS CLASS_DES,
  RETURNN.REASON_DESCRIPTION as REASON_DESCRIPTION,
  
   SUM(Sal_table.A_EXT_PR - A_EXT_DISC - (A_EXT_DISC*P_DISC/100)) AS refund_price
  -- COUNT ( DISTINCT Ref_table.M_TRN_ID ) AS Refund
   FROM KSFPA.IPS_SALES.TRN_REFUND Ref_table
// TO CONNECT SALES WITH REFUND TABLE
   INNER JOIN KSFPA.IPS_SALES.TRN_DETAIL Sal_table
   ON Ref_table.M_TRN_ID =Sal_table.M_TRN_ID
   AND Ref_table.M_STORE=Sal_table.M_STORE
   AND Ref_table.M_KD=Sal_table.M_KD
//TO GET CLASS AND DEPARMENT VALUE
   INNER JOIN KSFPA.MR2C.KEYCODE keycode
   ON Ref_table.M_KD=keycode.PRODUCT_SOURCE_IDENTIFIER
 
  -----
  LEFT JOIN KSF_SOPHIA_DATA_INTELLIGENCE_HUB_PROD.SALES.DIM_RETURN_REASON RETURNN
  ON RETURNN.REASON_CODE=cast(Ref_table.RETURNREASONCODE as VARCHAR(50))
  ----
  
   WHERE Ref_table.D_TRN_DATE BETWEEN '2023-01-01' AND '2023-06-30'
   AND Ref_table.M_PURCHASE_FROM_STORE < 9999
   GROUP BY 1,2,3,4,5,6
  
) REFUND_TABLE
GROUP BY 1,2,3,4,5  
