 SELECT 
 REFUND.DEPARTMENT,
 REFUND.DEPARTMENT_DES,
 REFUND.CLASS,
 REFUND.CLASS_DES,
  REFUND.REASON,
 COALESCE(TRIM(SALES.CARRIER),'NONE') AS Courier,
 SUM (REFUND.refund_price) AS refund_price
 FROM  
 (
-----table2-------------
 SELECT
  --DIM_TABLE.LOCATION_CODE AS LOC,
   Dim_reason.REASON_DESCRIPTION AS REASON,
  DD_EXTERNALORDERID AS EXTERNALORDERID,
  DIM_PROD.PRODUCT_KEYCODE AS PRODUCT_KEYCODE ,
  DIM_PROD.DEPARTMENT_CODE as DEPARTMENT,
  DIM_PROD.CLASS_CODE as CLASS,
  DIM_PROD.DEPARTMENT_DESCRIPTION as DEPARTMENT_DES,
  DIM_PROD.CLASS_DESCRIPTION as CLASS_DES,
  SUM(TOTAL_SELLING_PRICE_WITH_GST) as refund_price
  FROM KSF_SOPHIA_DATA_INTELLIGENCE_HUB_PROD.SALES.FACT_SALES_DETAIL ON_TABLE
	
    --INNER JOIN KSF_SOPHIA_DATA_INTELLIGENCE_HUB_PROD.COMMON_DIMENSIONS.DIM_LOCATION DIM_TABLE 
   -- ON ON_TABLE.FK_LOCATION_ID = DIM_TABLE.SK_LOCATION_ID
    INNER JOIN KSF_SOPHIA_DATA_INTELLIGENCE_HUB_PROD.COMMON_DIMENSIONS.DIM_PRODUCT DIM_PROD
    ON ON_TABLE.FK_PRODUCT_ID=DIM_PROD.SK_PRODUCT_ID
     Inner join KSF_SOPHIA_DATA_INTELLIGENCE_HUB_PROD.SALES.DIM_RETURN_REASON Dim_reason 
     On ON_TABLE.FK_RETURN_REASON_ID =Dim_reason.SK_RETURN_REASON_ID
    
    WHERE FK_DATE_ID BETWEEN '20230101' AND '20230630'
   AND DD_EXTERNALORDERID >0
  -- AND DD_REFUND_ORGINAL_TRANSACTION_NUMBER>0
    AND TRANSACTION_VOIDED = 0
    AND TRANSACTION_SUSPENDED = 0
    AND TRANSACTION_GIFTVOUCHER = 0
    AND TRANSACTION_GIFTCARD = 0
   AND FK_SOURCE_SYSTEM_ID = 15
    AND FK_TRANSACTION_TYPE_ID <> 3701
    AND QUANTITY_SOLD < 0
    GROUP BY 1,2,3,4,5,6,7
  ) REFUND
 
 Left Join 
 
 (
 -------Table1-------
   SELECT DISTINCT 
   TABA.EXTERNALORDERID AS EXTORDID,
   TABA.PRODUCT_KEYCODE AS PROD,
   OMS_TABLE.CARRIER AS CARRIER
  FROM  (
        SELECT DISTINCT
        DIM_PROD.PRODUCT_KEYCODE AS PRODUCT_KEYCODE ,
        DIM_LOC.LOCATION_CODE AS STR_ID,
        DD_EXTERNALORDERID AS EXTERNALORDERID,
        DD_ORDERID AS ORDERID
        FROM KSF_SOPHIA_DATA_INTELLIGENCE_HUB_PROD.SALES.FACT_SALES_DETAIL ON_TABLE

        INNER JOIN KSF_SOPHIA_DATA_INTELLIGENCE_HUB_PROD.COMMON_DIMENSIONS.DIM_PRODUCT DIM_PROD
        ON ON_TABLE.FK_PRODUCT_ID=DIM_PROD.SK_PRODUCT_ID
        INNER JOIN KSF_SOPHIA_DATA_INTELLIGENCE_HUB_PROD.COMMON_DIMENSIONS.DIM_LOCATION DIM_LOC 
        ON ON_TABLE.FK_LOCATION_ID = DIM_LOC.SK_LOCATION_ID

     WHERE FK_DATE_ID BETWEEN '20220701' AND '20230630'
     AND DD_EXTERNALORDERID >0
  
     AND TRANSACTION_VOIDED = 0
     AND TRANSACTION_SUSPENDED = 0
     AND TRANSACTION_GIFTVOUCHER = 0
     AND TRANSACTION_GIFTCARD = 0
     AND FK_SOURCE_SYSTEM_ID = 15
     AND FK_TRANSACTION_TYPE_ID <> 3701
     AND DD_ORDERID > 0
     AND QUANTITY_SOLD > 0
        
  )TABA
  INNER JOIN 
    (
     SELECT DISTINCT STR_ID,ORDERID,CARRIER 
     FROM KSFPA.OMS.STOREORDER 
    )OMS_TABLE
    ON OMS_TABLE.STR_ID=TABA.STR_ID
    AND OMS_TABLE.ORDERID=TABA.ORDERID
  -------------- 
  )SALES
  
 ON REFUND.EXTERNALORDERID = SALES.EXTORDID
 AND REFUND.PRODUCT_KEYCODE =SALES.PROD
 
 WHERE REFUND.refund_price <> 0
 GROUP BY 1,2,3,4,5,6