--------- For Online------
SELECT 
COALESCE(Refund.DEPARTMENT,Sales.DEPARTMENT) AS DEPARTMENT,
COALESCE(Refund.DEPARTMENT_DES,Sales.DEPARTMENT_DES) as DEPARTMENT_DES,
COALESCE(Refund.CLASS,Sales.CLASS) as CLASS,
COALESCE(Refund.CLASS_DES,Sales.CLASS_DES) as CLASS_DES,
COALESCE(Refund.Courier,Sales.Courier) as Courier,
--Refund.REASON_DESCRIPTION,
--SUM(Refund.REFUND_TRN_ID_COUNT ) AS REFUND_TRN_ID_COUNT,
SUM(IFNULL(Refund.refund_price,0) )AS refund_price,
--SUM(Sales.SALES_TRN_ID_COUNT) AS SALES_TRN_ID_COUNT,
SUM(IFNULL(Sales.sales_price,0)) AS sales_price
FROM
(
     SELECT 
 REFUND.DEPARTMENT,
 REFUND.DEPARTMENT_DES,
 REFUND.CLASS,
 REFUND.CLASS_DES,
 COALESCE(TRIM(SALES.CARRIER),'NONE') AS Courier,
  SUM (REFUND.refund_price) AS refund_price
 FROM  
 (
-----table2-------------
 SELECT
  --DIM_TABLE.LOCATION_CODE AS LOC,
  DD_EXTERNALORDERID AS EXTERNALORDERID,
  DIM_PROD.PRODUCT_KEYCODE AS PRODUCT_KEYCODE ,
  DIM_PROD.DEPARTMENT_CODE as DEPARTMENT,
  DIM_PROD.CLASS_CODE as CLASS,
  DIM_PROD.DEPARTMENT_DESCRIPTION as DEPARTMENT_DES,
  DIM_PROD.CLASS_DESCRIPTION as CLASS_DES,
  SUM(TOTAL_SELLING_PRICE_WITH_GST) as refund_price
  FROM KSF_SOPHIA_DATA_INTELLIGENCE_HUB_PROD.SALES.FACT_SALES_DETAIL ON_TABLE
	
    --INNER JOIN KSF_SOPHIA_DATA_INTELLIGENCE_HUB_PROD.COMMON_DIMENSIONS.DIM_LOCATION DIM_TABLE 
   -- ON ON_TABLE.FK_LOCATION_ID = DIM_TABLE.SK_LOCATION_ID
    INNER JOIN KSF_SOPHIA_DATA_INTELLIGENCE_HUB_PROD.COMMON_DIMENSIONS.DIM_PRODUCT DIM_PROD
    ON ON_TABLE.FK_PRODUCT_ID=DIM_PROD.SK_PRODUCT_ID
    
    WHERE FK_DATE_ID BETWEEN '20230101' AND '20230630'
   AND DD_EXTERNALORDERID >0
  -- AND DD_REFUND_ORGINAL_TRANSACTION_NUMBER>0
    AND TRANSACTION_VOIDED = 0
    AND TRANSACTION_SUSPENDED = 0
    AND TRANSACTION_GIFTVOUCHER = 0
    AND TRANSACTION_GIFTCARD = 0
   AND FK_SOURCE_SYSTEM_ID = 15
    AND FK_TRANSACTION_TYPE_ID <> 3701
    AND QUANTITY_SOLD < 0
    GROUP BY 1,2,3,4,5,6
  ) REFUND
 
 Left Join 
 
 (
 -------Table1-------
   SELECT DISTINCT 
   TABA.EXTERNALORDERID AS EXTORDID,
   TABA.PRODUCT_KEYCODE AS PROD,
   OMS_TABLE.CARRIER AS CARRIER
  FROM  (
        SELECT DISTINCT
        DIM_PROD.PRODUCT_KEYCODE AS PRODUCT_KEYCODE ,
        DIM_LOC.LOCATION_CODE AS STR_ID,
        DD_EXTERNALORDERID AS EXTERNALORDERID,
        DD_ORDERID AS ORDERID
        FROM KSF_SOPHIA_DATA_INTELLIGENCE_HUB_PROD.SALES.FACT_SALES_DETAIL ON_TABLE

        INNER JOIN KSF_SOPHIA_DATA_INTELLIGENCE_HUB_PROD.COMMON_DIMENSIONS.DIM_PRODUCT DIM_PROD
        ON ON_TABLE.FK_PRODUCT_ID=DIM_PROD.SK_PRODUCT_ID
        INNER JOIN KSF_SOPHIA_DATA_INTELLIGENCE_HUB_PROD.COMMON_DIMENSIONS.DIM_LOCATION DIM_LOC 
        ON ON_TABLE.FK_LOCATION_ID = DIM_LOC.SK_LOCATION_ID

     WHERE FK_DATE_ID BETWEEN '20220701' AND '20230630'
     AND DD_EXTERNALORDERID >0
  
     AND TRANSACTION_VOIDED = 0
     AND TRANSACTION_SUSPENDED = 0
     AND TRANSACTION_GIFTVOUCHER = 0
     AND TRANSACTION_GIFTCARD = 0
     AND FK_SOURCE_SYSTEM_ID = 15
     AND FK_TRANSACTION_TYPE_ID <> 3701
     AND DD_ORDERID > 0
     AND QUANTITY_SOLD > 0
        
  )TABA
  INNER JOIN 
    (
     SELECT DISTINCT STR_ID,ORDERID,CARRIER 
     FROM KSFPA.OMS.STOREORDER 
    )OMS_TABLE
    ON OMS_TABLE.STR_ID=TABA.STR_ID
    AND OMS_TABLE.ORDERID=TABA.ORDERID
  -------------- 
  )SALES
  
 ON REFUND.EXTERNALORDERID = SALES.EXTORDID
 AND REFUND.PRODUCT_KEYCODE =SALES.PROD
 
 WHERE REFUND.refund_price <> 0
  GROUP BY 1,2,3,4,5
 ) Refund

FULL OUTER JOIN
( 
SELECT 
  -- DIM_TABLE.LOCATION_CODE,
   keycode.DEPARTMENT_CODE AS DEPARTMENT,
   keycode.CLASS_CODE AS CLASS,
   keycode.DEPARTMENT_DESCRIPTION AS DEPARTMENT_DES,
   keycode.CLASS_DESCRIPTION AS CLASS_DES,
   COALESCE(TRIM(OMS_TABLE.CARRIER),'NONE') AS Courier,
   SUM(TOTAL_SELLING_PRICE_WITH_GST) AS sales_price
   --COUNT(DISTINCT DD_EXTERNALORDERID)AS SALES_TRN_ID_COUNT
   FROM KSF_SOPHIA_DATA_INTELLIGENCE_HUB_PROD.SALES.FACT_SALES_DETAIL ON_TABLE
  
 
   INNER join KSF_SOPHIA_DATA_INTELLIGENCE_HUB_PROD.COMMON_DIMENSIONS.DIM_LOCATION DIM_TABLE
   ON ON_TABLE.FK_LOCATION_ID = DIM_TABLE.SK_LOCATION_ID
  
   LEFT JOIN  (select distinct STR_ID,ORDERID,CARRIER from KSFPA.OMS.STOREORDER
  where TRIM(ORDERSTATUS) IN ('OrderShipped','OrderCollected','OrdedrShipped')
  ) OMS_TABLE
   ON DIM_TABLE.LOCATION_CODE=OMS_TABLE.STR_ID 
  --ON DIM_TABLE.LOCATION_CODE=cast(OMS_TABLE.STR_ID as Varchar(100))
  AND ON_TABLE.DD_ORDERID=OMS_TABLE.ORDERID
    
   INNER JOIN  KSF_SOPHIA_DATA_INTELLIGENCE_HUB_PROD.COMMON_DIMENSIONS.DIM_PRODUCT keycode
   ON ON_TABLE.FK_PRODUCT_ID=keycode.SK_PRODUCT_ID
    
   WHERE FK_DATE_ID BETWEEN '20230101' AND '20230630'
  
  -- AND DEPARTMENT_DESCRIPTION ='ACTION/VEHICLE TOY'
  --AND CLASS_DESCRIPTION= 'ACTION FIGURES'
   AND TRANSACTION_VOIDED = 0
   AND TRANSACTION_SUSPENDED = 0
   AND TRANSACTION_GIFTVOUCHER = 0
   AND TRANSACTION_GIFTCARD = 0
   AND FK_SOURCE_SYSTEM_ID = 15
   AND FK_TRANSACTION_TYPE_ID <> 3701
  AND DD_ORDERID > 0
   AND QUANTITY_SOLD > 0
   GROUP BY 1,2,3,4,5
) Sales
   --ON Refund.LOCATION_CODE=Sales.LOCATION_CODE
   on Refund.DEPARTMENT=Sales.DEPARTMENT
   AND Refund.CLASS=Sales.CLASS
   AND Refund.Courier=Sales.Courier
   GROUP  BY 1,2,3,4,5