--- VIC NUMBERS---

SELECT *
FROM 
(SELECT DS.LOCATION_GENERATED_IDENTIFIER 
				, DS.PRODUCT_GENERATED_IDENTIFIER 
				, DAY_DATE
				, DAILY_STOCK_ON_HAND_QUANTITY
				, NET_SHRINK_VALUE
				, NET_SHRINK_QTY
			FROM KSFPA.MR2C.DAILY_SOH DS
			INNER JOIN KSFPA.MR2C."LOCATION" LOC
			ON DS.LOCATION_GENERATED_IDENTIFIER = LOC.LOCATION_GENERATED_IDENTIFIER 
			INNER JOIN KSFPA.MR2C.KEYCODE KC 
			ON DS.PRODUCT_GENERATED_IDENTIFIER = KC.PRODUCT_GENERATED_IDENTIFIER
--IDENTIFYING +tv SHRINK QTY 
INNER JOIN (SELECT *
			FROM
				(
					SELECT  SS.PRODUCT_GENERATED_IDENTIFIER 
							, SUM(STOCK_ADJUSTMENT_COST_AMOUNT) AS NET_SHRINK_VALUE
							, SUM(STOCK_ADJUSTMENT_QUANTITY) AS NET_SHRINK_QTY
					FROM KSFPA.MR2.SS_STOCK_ADJUSTMENT SS 
					INNER JOIN KSFPA.MR2C."LOCATION" LOC
					ON SS.LOCATION_GENERATED_IDENTIFIER = LOC.LOCATION_GENERATED_IDENTIFIER 
					INNER JOIN KSFPA.MR2C.KEYCODE KC
					ON SS.PRODUCT_GENERATED_IDENTIFIER = KC.PRODUCT_GENERATED_IDENTIFIER
					INNER JOIN KSFPA.LOSS_PREVENTION_PVT.DEPARTMENT_GM_APPAREL_CATEGORY APP_GM
					ON KC.DEPARTMENT_SOURCE_IDENTIFIER = APP_GM.DEPARTMENT_SOURCE_IDENTIFIER
					WHERE LOC.LOCATION_SOURCE_IDENTIFIER = 9324
					AND PERIOD_END_DATE > '2022-02-20'
					AND STOCK_ADJUSTMENT_REASON_CODE = '36'
					AND CATEGORY = 'GM'
					GROUP BY 1)
			WHERE NET_SHRINK_QTY > 0) SHK
ON DS.PRODUCT_GENERATED_IDENTIFIER = SHK.PRODUCT_GENERATED_IDENTIFIER
AND DAY_DATE = '2022-11-14'
AND STATE = 'VIC'
AND DAILY_STOCK_ON_HAND_QUANTITY <0
ORDER BY DS.LOCATION_GENERATED_IDENTIFIER, DS.PRODUCT_GENERATED_IDENTIFIER )


--NSW NUMBERS
SELECT *
			FROM 
			(SELECT DS.LOCATION_GENERATED_IDENTIFIER 
							, DS.PRODUCT_GENERATED_IDENTIFIER 
							, DAY_DATE
							, DAILY_STOCK_ON_HAND_QUANTITY
							, NET_SHRINK_VALUE
							, NET_SHRINK_QTY
						FROM KSFPA.MR2C.DAILY_SOH DS
						INNER JOIN KSFPA.MR2C."LOCATION" LOC
						ON DS.LOCATION_GENERATED_IDENTIFIER = LOC.LOCATION_GENERATED_IDENTIFIER 
						INNER JOIN KSFPA.MR2C.KEYCODE KC 
						ON DS.PRODUCT_GENERATED_IDENTIFIER = KC.PRODUCT_GENERATED_IDENTIFIER
			--IDENTIFYING +tv SHRINK QTY 
			INNER JOIN (SELECT * 
						FROM
							(
								SELECT  SS.PRODUCT_GENERATED_IDENTIFIER 
										, SUM(STOCK_ADJUSTMENT_COST_AMOUNT) AS NET_SHRINK_VALUE
										, SUM(STOCK_ADJUSTMENT_QUANTITY) AS NET_SHRINK_QTY
								FROM KSFPA.MR2.SS_STOCK_ADJUSTMENT SS 
								INNER JOIN KSFPA.MR2C."LOCATION" LOC
								ON SS.LOCATION_GENERATED_IDENTIFIER = LOC.LOCATION_GENERATED_IDENTIFIER 
								INNER JOIN KSFPA.MR2C.KEYCODE KC
								ON SS.PRODUCT_GENERATED_IDENTIFIER = KC.PRODUCT_GENERATED_IDENTIFIER
								INNER JOIN KSFPA.LOSS_PREVENTION_PVT.DEPARTMENT_GM_APPAREL_CATEGORY APP_GM
								ON KC.DEPARTMENT_SOURCE_IDENTIFIER = APP_GM.DEPARTMENT_SOURCE_IDENTIFIER
								WHERE LOC.LOCATION_SOURCE_IDENTIFIER = 9324
								AND PERIOD_END_DATE > '2022-02-20'
								AND STOCK_ADJUSTMENT_REASON_CODE = '36'
								AND CATEGORY = 'GM'
								GROUP BY 1)
						WHERE NET_SHRINK_QTY > 0) SHK
			ON DS.PRODUCT_GENERATED_IDENTIFIER = SHK.PRODUCT_GENERATED_IDENTIFIER
			AND DAY_DATE = '2022-11-14'
			AND STATE = 'NSW'
			AND DAILY_STOCK_ON_HAND_QUANTITY <0
			ORDER BY DS.LOCATION_GENERATED_IDENTIFIER, DS.PRODUCT_GENERATED_IDENTIFIER)