CREATE OR REPLACE TABLE KSFDA.SHRINK_TACTICAL.PAPER_SHRINK_COST_ADJUSTMENT AS
(
SELECT a.*, b.adjustment,
	IFF(abs(ADJUSTMENT) = abs(a.DIFF_MANIFEST), a.DIFF_MANIFEST * LOCATION_AWC_AMOUNT, 0) AS NEW_MANIFEST_COST,
	IFF(abs(ADJUSTMENT) = abs(a.DIFF_MANIFEST), a.DIFF_MANIFEST, 0) AS NEW_DIFF_MANIFEST,
	IFF(abs(ADJUSTMENT) = abs(a.DIFF_SALES), a.DIFF_SALES * LOCATION_AWC_AMOUNT, 0) AS NEW_SALES_COST,
	IFF(abs(ADJUSTMENT) = abs(a.DIFF_SALES), a.DIFF_SALES, 0) AS NEW_DIFF_SALES,
	IFF(abs(ADJUSTMENT) = abs(a.DIFF_SHRINK), a.DIFF_SHRINK * LOCATION_AWC_AMOUNT, 0) AS NEW_SHRINK_COST,
	IFF(abs(ADJUSTMENT) = abs(a.DIFF_SHRINK), a.DIFF_SHRINK, 0) AS NEW_DIFF_SHRINK,
	IFF(abs(ADJUSTMENT) = abs(a.DIFF_ITC), a.DIFF_ITC * LOCATION_AWC_AMOUNT, 0) AS NEW_ITC_COST,
	IFF(abs(ADJUSTMENT) = abs(a.DIFF_ITC), a.DIFF_ITC, 0) AS NEW_DIFF_ITC,
	IFF(abs(ADJUSTMENT) = abs(a.DIFF_RLO), a.DIFF_RLO * LOCATION_AWC_AMOUNT, 0) AS NEW_RLO_COST,
	IFF(abs(ADJUSTMENT) = abs(a.DIFF_RLO), a.DIFF_RLO, 0) AS NEW_DIFF_RLO,
	IFF(abs(ADJUSTMENT) = abs(a.DIFF_PO), a.DIFF_PO * LOCATION_AWC_AMOUNT, 0) AS NEW_PO_COST,
	IFF(abs(ADJUSTMENT) = abs(a.DIFF_PO), a.DIFF_PO, 0) AS NEW_DIFF_PO
FROM KSFDA.SHRINK_TACTICAL.PAPER_SHRINK_COST_ANALYSIS_Step_1_6 a
JOIN KSFDA.SHRINK_TACTICAL.SUMMARY_PAGE_ADJUSTMENT b
ON a.PRODUCT_GENERATED_IDENTIFIER = b.PRODUCT_GENERATED_IDENTIFIER
AND a.LOCATION_GENERATED_IDENTIFIER = b.LOCATION_GENERATED_IDENTIFIER
--WHERE a.PRODUCT_GENERATED_IDENTIFIER = '4317562800004' 
--AND a.LOCATION_GENERATED_IDENTIFIER = '1040136000001'
)
