CREATE TABLE KSFDA.SHRINK_TACTICAL.PAPER_SHRINK_COST_ANALYSIS_Step_1_6 AS
(
SELECT A.*, AWC.LOCATION_AWC_AMOUNT,
DATEADD (DAY,-6 - DAYOFWEEK (TO_DATE(A.DATE_)),TO_DATE(A.DATE_)) AS WEEK_START_DATE,
	((IPS_Manifest- MR_MANIFEST)) as DIFF_MANIFEST, --LOCATION_AWC_AMOUNT * DIFF_MANIFEST AS MANIFEST_COST,
	IFF((A.DATE_ >= '2022-02-20' AND A.DATE_ <= '2022-03-06') OR (A.DATE_ >= '2023-02-12' AND A.DATE_ <= '2023-02-26'),0,LOCATION_AWC_AMOUNT * DIFF_MANIFEST) AS MANIFEST_COST,
	((IPS_Sales- MR_SALES)) as DIFF_SALES, --LOCATION_AWC_AMOUNT * DIFF_SALES AS SALES_COST,
	IFF((A.DATE_ >= '2022-02-20' AND A.DATE_ <= '2022-03-06') OR (A.DATE_ >= '2023-02-12' AND A.DATE_ <= '2023-02-26'),0,LOCATION_AWC_AMOUNT * DIFF_SALES) AS SALES_COST,
	((IPS_SHRINK- MR_SHRINK)) as DIFF_SHRINK, --LOCATION_AWC_AMOUNT * DIFF_SHRINK AS SHRINK_COST,
	IFF((A.DATE_ >= '2022-02-20' AND A.DATE_ <= '2022-03-06') OR (A.DATE_ >= '2023-02-12' AND A.DATE_ <= '2023-02-26'),0,LOCATION_AWC_AMOUNT * DIFF_SHRINK) AS SHRINK_COST,
	((IPS_ITC- MR_ITC)) as DIFF_ITC, --LOCATION_AWC_AMOUNT * DIFF_ITC AS ITC_COST,
	IFF((A.DATE_ >= '2022-02-20' AND A.DATE_ <= '2022-03-06') OR (A.DATE_ >= '2023-02-12' AND A.DATE_ <= '2023-02-26'),0,LOCATION_AWC_AMOUNT * DIFF_ITC) AS ITC_COST,
	((IPS_RLO- MR_RLO)) as DIFF_RLO, --LOCATION_AWC_AMOUNT * DIFF_RLO AS RLO_COST,
	IFF((A.DATE_ >= '2022-02-20' AND A.DATE_ <= '2022-03-06') OR (A.DATE_ >= '2023-02-12' AND A.DATE_ <= '2023-02-26'),0,LOCATION_AWC_AMOUNT * DIFF_RLO) AS RLO_COST,
	((IPS_PO- MR_PO)) as DIFF_PO, --LOCATION_AWC_AMOUNT * DIFF_PO AS PO_COST,
	IFF((A.DATE_ >= '2022-02-20' AND A.DATE_ <= '2022-03-06') OR (A.DATE_ >= '2023-02-12' AND A.DATE_ <= '2023-02-26'),0,LOCATION_AWC_AMOUNT * DIFF_PO) AS PO_COST,
	  --0 AS PO_COST,
	((IPS_Derived_SOH - MR_Derived_SOH)) as DIFF_SOH
FROM KSFDA.SHRINK_TACTICAL.PAPER_SHRINK_DETAILED6 A
JOIN KSFPA.MR2.SS_AVERAGE_WEIGHTED_COST AWC
ON A.PRODUCT_GENERATED_IDENTIFIER = AWC.PRODUCT_GENERATED_IDENTIFIER
AND A.LOCATION_GENERATED_IDENTIFIER = AWC.LOCATION_GENERATED_IDENTIFIER
AND AWC.EFFECTIVE_DATE <= A.DATE_
AND AWC.EXPIRY_DATE >= DATEADD (DAY,-6 - DAYOFWEEK (TO_DATE(A.DATE_)),TO_DATE(A.DATE_))
order by DATE_
)
