CREATE TABLE KSFDA.SHRINK_TACTICAL.PAPER_SHRINK_COST_ESTIMATE_ADJUSTMENT AS
( 
SELECT 'TOTAL_SOH' AS REASON,
       SUM(NEGATIVE_UNITS) AS NEGATIVE_UNITS,
       SUM(NEGATIVE_COST) AS NEGATIVE_COST,
       SUM(POSITIVE_UNITS) AS POSITIVE_UNITS,
       SUM(POSITIVE_COST) AS POSITIVE_COST
FROM(
SELECT *
FROM
  (SELECT 'TOTAL_MANIFEST ' AS REASON,
          SUM(NEW_DIFF_MANIFEST) AS NEGATIVE_UNITS,
          SUM(MANIFEST_COST) AS NEGATIVE_COST
   FROM KSFDA.SHRINK_TACTICAL.PAPER_SHRINK_COST_ANALYSIS_Step_2_ADJUSTMENT
   WHERE FLAG_MANIFEST = 1
     AND NEW_DIFF_MANIFEST <0)a,
  (SELECT SUM(NEW_DIFF_MANIFEST) AS POSITIVE_UNITS,
          SUM(MANIFEST_COST) AS POSITIVE_COST
   FROM KSFDA.SHRINK_TACTICAL.PAPER_SHRINK_COST_ANALYSIS_Step_2_ADJUSTMENT
   WHERE FLAG_MANIFEST = 1
     AND NEW_DIFF_MANIFEST >= 0)bUNION

SELECT *
FROM
  (SELECT 'TOTAL_SALES ' AS REASON,
          SUM(NEW_DIFF_SALES) AS NEGATIVE_UNITS,
          SUM(SALES_COST) AS NEGATIVE_COST
   FROM KSFDA.SHRINK_TACTICAL.PAPER_SHRINK_COST_ANALYSIS_Step_2_ADJUSTMENT
   WHERE FLAG_SALES = 1
     AND NEW_DIFF_SALES <0)a,
  (SELECT SUM(NEW_DIFF_SALES) AS POSITIVE_UNITS,
          SUM(SALES_COST) AS POSITIVE_COST
   FROM KSFDA.SHRINK_TACTICAL.PAPER_SHRINK_COST_ANALYSIS_Step_2_ADJUSTMENT
   WHERE FLAG_SALES = 1
     AND NEW_DIFF_SALES >= 0) b
  
UNION

SELECT *
FROM
  (SELECT 'TOTAL_SHRINK ' AS REASON,
          SUM(NEW_DIFF_SHRINK) AS NEGATIVE_UNITS,
          SUM(SHRINK_COST) AS NEGATIVE_COST
   FROM KSFDA.SHRINK_TACTICAL.PAPER_SHRINK_COST_ANALYSIS_Step_2_ADJUSTMENT
   WHERE FLAG_SHRINK = 1
     AND NEW_DIFF_SHRINK <0)a,

(
SELECT SUM(NEW_DIFF_SHRINK) AS POSITIVE_UNITS,
       SUM(SHRINK_COST) AS POSITIVE_COST

FROM KSFDA.SHRINK_TACTICAL.PAPER_SHRINK_COST_ANALYSIS_Step_2_ADJUSTMENT
WHERE FLAG_SHRINK = 1
  AND NEW_DIFF_SHRINK >= 0)b

UNION

SELECT *
FROM
  (SELECT 'TOTAL_PO ' AS REASON,
          SUM(NEW_DIFF_PO) AS NEGATIVE_UNITS,
          SUM(PO_COST) AS NEGATIVE_COST
   FROM KSFDA.SHRINK_TACTICAL.PAPER_SHRINK_COST_ANALYSIS_Step_2_ADJUSTMENT
   WHERE FLAG_PO = 1
     AND NEW_DIFF_PO <0)a,
  (SELECT SUM(NEW_DIFF_PO) AS POSITIVE_UNITS,
          SUM(PO_COST) AS POSITIVE_COST
   FROM KSFDA.SHRINK_TACTICAL.PAPER_SHRINK_COST_ANALYSIS_Step_2_ADJUSTMENT
   WHERE FLAG_PO = 1
     AND NEW_DIFF_PO >= 0)b
UNION
SELECT *
FROM
  (SELECT 'TOTAL_RLO ' AS REASON,
          SUM(NEW_DIFF_RLO) AS NEGATIVE_UNITS,
          SUM(RLO_COST) AS NEGATIVE_COST
   FROM KSFDA.SHRINK_TACTICAL.PAPER_SHRINK_COST_ANALYSIS_Step_2_ADJUSTMENT
   WHERE FLAG_RLO = 1
     AND NEW_DIFF_RLO <0)a,
  (SELECT SUM(NEW_DIFF_RLO) AS POSITIVE_UNITS,
          SUM(RLO_COST) AS POSITIVE_COST
   FROM KSFDA.SHRINK_TACTICAL.PAPER_SHRINK_COST_ANALYSIS_Step_2_ADJUSTMENT
   WHERE FLAG_RLO = 1
     AND NEW_DIFF_RLO >= 0)b )
UNION
SELECT *
FROM
  (SELECT 'TOTAL_MANIFEST ' AS REASON,
          SUM(NEW_DIFF_MANIFEST) AS NEGATIVE_UNITS,
          SUM(MANIFEST_COST) AS NEGATIVE_COST
   FROM KSFDA.SHRINK_TACTICAL.PAPER_SHRINK_COST_ANALYSIS_Step_2_ADJUSTMENT
   WHERE FLAG_MANIFEST = 1
     AND NEW_DIFF_MANIFEST <0)a,
  (SELECT SUM(NEW_DIFF_MANIFEST) AS POSITIVE_UNITS,
          SUM(MANIFEST_COST) AS POSITIVE_COST
   FROM KSFDA.SHRINK_TACTICAL.PAPER_SHRINK_COST_ANALYSIS_Step_2_ADJUSTMENT
   WHERE FLAG_MANIFEST = 1
     AND NEW_DIFF_MANIFEST >= 0)b
UNION
SELECT *
FROM
  (SELECT 'TOTAL_SALES ' AS REASON,
          SUM(NEW_DIFF_SALES) AS NEGATIVE_UNITS,
          SUM(SALES_COST) AS NEGATIVE_COST
   FROM KSFDA.SHRINK_TACTICAL.PAPER_SHRINK_COST_ANALYSIS_Step_2_ADJUSTMENT
   WHERE FLAG_SALES = 1
     AND NEW_DIFF_SALES <0)a,
  (SELECT SUM(NEW_DIFF_SALES) AS POSITIVE_UNITS,
          SUM(SALES_COST) AS POSITIVE_COST
   FROM KSFDA.SHRINK_TACTICAL.PAPER_SHRINK_COST_ANALYSIS_Step_2_ADJUSTMENT
   WHERE FLAG_SALES = 1
     AND NEW_DIFF_SALES >= 0)b
UNION
SELECT *
FROM
  (SELECT 'TOTAL_SHRINK ' AS REASON,
          SUM(NEW_DIFF_SHRINK) AS NEGATIVE_UNITS,
          SUM(SHRINK_COST) AS NEGATIVE_COST
   FROM KSFDA.SHRINK_TACTICAL.PAPER_SHRINK_COST_ANALYSIS_Step_2_ADJUSTMENT
   WHERE FLAG_SHRINK = 1
     AND NEW_DIFF_SHRINK <0)a,
  (SELECT SUM(NEW_DIFF_SHRINK) AS POSITIVE_UNITS,
          SUM(SHRINK_COST) AS POSITIVE_COST
   FROM KSFDA.SHRINK_TACTICAL.PAPER_SHRINK_COST_ANALYSIS_Step_2_ADJUSTMENT
   WHERE FLAG_SHRINK = 1
     AND NEW_DIFF_SHRINK >= 0)b
UNION
SELECT *
FROM
  (SELECT 'TOTAL_PO ' AS REASON,
          SUM(NEW_DIFF_PO) AS NEGATIVE_UNITS,
          SUM(PO_COST) AS NEGATIVE_COST
   FROM KSFDA.SHRINK_TACTICAL.PAPER_SHRINK_COST_ANALYSIS_Step_2_ADJUSTMENT
   WHERE FLAG_PO = 1
     AND NEW_DIFF_PO <0)a,
  (SELECT SUM(NEW_DIFF_PO) AS POSITIVE_UNITS,
          SUM(PO_COST) AS POSITIVE_COST
   FROM KSFDA.SHRINK_TACTICAL.PAPER_SHRINK_COST_ANALYSIS_Step_2_ADJUSTMENT
   WHERE FLAG_PO = 1
     AND NEW_DIFF_PO >= 0)b
UNION
SELECT *
FROM
  (SELECT 'TOTAL_RLO ' AS REASON,
          SUM(NEW_DIFF_RLO) AS NEGATIVE_UNITS,
          SUM(RLO_COST) AS NEGATIVE_COST
   FROM KSFDA.SHRINK_TACTICAL.PAPER_SHRINK_COST_ANALYSIS_Step_2_ADJUSTMENT
   WHERE FLAG_RLO = 1
     AND NEW_DIFF_RLO <0)a,
  (SELECT SUM(NEW_DIFF_RLO) AS POSITIVE_UNITS,
          SUM(RLO_COST) AS POSITIVE_COST
   FROM KSFDA.SHRINK_TACTICAL.PAPER_SHRINK_COST_ANALYSIS_Step_2_ADJUSTMENT
   WHERE FLAG_RLO = 1
     AND NEW_DIFF_RLO >= 0)b )