-- Code to get the top 100 adjusted keycodes removing ghost adjustments by frequency and quantity:
SELECT A.PRODUCT_GENERATED_IDENTIFIER, A.PRODUCT_DESCRIPTION, A.DEPARTMENT_DESCRIPTION, A.DEPARTMENT_SOURCE_IDENTIFIER,
KEYCODE_OCCURRENCE AS KEYCODE_FREQUENCY, TOT_RFID_ADJ_QTY, TOT_ABS_RFID_ADJ_QTY,
RANK() OVER (ORDER BY KEYCODE_OCCURRENCE DESC) AS FREQUENCY_RNK,
RANK() OVER (ORDER BY TOT_ABS_RFID_ADJ_QTY DESC) AS ADJ_QTY_RANK
FROM
(SELECT A.PRODUCT_GENERATED_IDENTIFIER, A.PRODUCT_DESCRIPTION, A.DEPARTMENT_DESCRIPTION, A.DEPARTMENT_SOURCE_IDENTIFIER,
COUNT(*) AS KEYCODE_OCCURRENCE,
SUM(ABS(A.RFID_ADJ_QTY)) AS TOT_ABS_RFID_ADJ_QTY,
SUM(A.RFID_ADJ_QTY) AS TOT_RFID_ADJ_QTY
FROM
(SELECT A.*
FROM
(SELECT A.LOCATION_GENERATED_IDENTIFIER, A.PRODUCT_GENERATED_IDENTIFIER,
B.DEPARTMENT_DESCRIPTION, B.DEPARTMENT_SOURCE_IDENTIFIER, B.PRODUCT_DESCRIPTION,
A.DAY_DATE, C.DAY_OF_WEEK_CODE, C.WEEK_END_DATE,
C.ACCOUNTING_WEEK_ID, C.ACCOUNTING_PERIOD_DESCRIPTION, C.CALENDAR_WEEK_ID,
SUM(A.STOCK_MOVEMENT_QUANTITY) AS RFID_ADJ_QTY
--ABS(SUM(A.STOCK_MOVEMENT_QUANTITY)) AS ABS_RFID_ADJ_QTY
FROM KSFPA.IPS_STOCK_AUDIT.IPS_STOCK_AUDIT A
INNER JOIN KSFPA.MR2C.KEYCODE B
ON A.PRODUCT_GENERATED_IDENTIFIER = B.PRODUCT_SOURCE_IDENTIFIER
INNER JOIN KSFPA.MR2C.DAY C
ON A.DAY_DATE = C.DAY_DATE
WHERE 
A.LOCATION_GENERATED_IDENTIFIER IN (1021,
1124,
1139,
1142,
1217,
1223,
1231) AND
TRANSACTION_USER_ID = 'RFID'
AND A.DAY_DATE >= '2022-01-03'
AND A.DAY_DATE <= '2022-04-17'
AND C.DAY_OF_WEEK_CODE NOT IN ('Sat', 'Sun')
GROUP BY 1,2,3,4,5,6,7,8,9,10,11) A
LEFT JOIN KSFPA.LOSS_PREVENTION_PVT.GHOST_RFID_DAY_ABS_ADJ_PROD_LOC B
ON A.LOCATION_GENERATED_IDENTIFIER = B.LOCATION_GENERATED_IDENTIFIER
AND A.PRODUCT_GENERATED_IDENTIFIER = B.PRODUCT_GENERATED_IDENTIFIER
AND A.DAY_DATE = B.DAY_DATE
WHERE B.ABS_RFID_ADJ IS NULL) A
GROUP BY 1,2,3,4) A;

