SELECT 
	MR.PRODUCT_GENERATED_IDENTIFIER AS PRODUCT_GENERATED_IDENTIFIER,
	MR.LOCATION_GENERATED_IDENTIFIER AS LOCATION_GENERATED_IDENTIFIER,
	IPS.PRODUCT_GENERATED_IDENTIFIER AS PRODUCT_SOURCE_IDENTIFIER,
	IPS.LOCATION_GENERATED_IDENTIFIER AS LOCATION_SOURCE_IDENTIFIER,
	'2022-03-28' AS START_DATE,
	'2023-04-02' AS END_DATE,
	LOC.LOCATION_NAME,
	LOC.STATE,
	KEY_CODE.PRODUCT_DESCRIPTION,
	KEY_CODE.DEPARTMENT_DESCRIPTION,
	IPS.IPS_MANIFEST,
	MR.MR_MANIFEST,
	IPS.IPS_SALES,
	MR.MR_SALES,
	IPS.IPS_SHRINK,
	MR.MR_SHRINK,
	IPS.IPS_ITC,
	MR.MR_ITC,
	IPS.IPS_RLO,
	MR.MR_RLO,
	IPS.IPS_PO,
	MR.MR_PO,
	IPS.IPS_DERIVED_SOH,
	MR.MR_DERIVED_SOH,
	(IPS_MANIFEST - MR_MANIFEST) AS DIFF_MANIFEST,
	(IPS_SALES - MR_SALES) AS DIFF_SALES,
	(IPS_SHRINK - MR_SHRINK) AS DIFF_SHRINK,
	(IPS_ITC - MR_ITC) AS DIFF_ITC,
	(IPS_RLO - MR_RLO) AS DIFF_RLO,
	(IPS_PO - MR_PO) AS DIFF_PO,
	(IPS_DERIVED_SOH - MR_DERIVED_SOH) AS DIFF_DERIVED_SOH,
	IFF(DIFF_MANIFEST != 0, 1, 0) AS FLAG_MANIFEST,
	IFF(DIFF_SALES != 0, 1, 0) AS FLAG_SALES,
	IFF(DIFF_SHRINK != 0, 1, 0) AS FLAG_SHRINK,
	IFF(DIFF_ITC != 0, 1, 0) AS FLAG_ITC,
	IFF(DIFF_RLO != 0, 1, 0) AS FLAG_RLO,
	IFF(DIFF_PO != 0, 1, 0) AS FLAG_PO,
	IFF(DIFF_DERIVED_SOH != 0, 1, 0) AS FLAG_DERIVED_SOH,
	IFF((ltrim(CASE WHEN FLAG_MANIFEST = 1 THEN 'MANIFEST' ELSE '' END||CASE WHEN FLAG_SALES = 1 THEN ',SALES' ELSE '' END ||CASE WHEN FLAG_SHRINK = 1 THEN ',SHRINK' ELSE '' END ||CASE WHEN FLAG_ITC = 1 THEN ',ITC' ELSE '' END ||CASE WHEN FLAG_RLO = 1 THEN ',RLO' ELSE '' END ||CASE WHEN FLAG_PO = 1 THEN ',PO' ELSE '' END, ',')) = '', NULL, (ltrim(CASE WHEN FLAG_MANIFEST = 1 THEN 'MANIFEST' ELSE '' END||CASE WHEN FLAG_SALES = 1 THEN ',SALES' ELSE '' END ||CASE WHEN FLAG_SHRINK = 1 THEN ',SHRINK' ELSE '' END ||CASE WHEN FLAG_ITC = 1 THEN ',ITC' ELSE '' END ||CASE WHEN FLAG_RLO = 1 THEN ',RLO' ELSE '' END ||CASE WHEN FLAG_PO = 1 THEN ',PO' ELSE '' END, ','))) AS FLAG_REASON
FROM KSFDA.SHRINK_TACTICAL.IPS_DATA IPS
JOIN KSFDA.SHRINK_TACTICAL.MR_DATA MR
ON TO_NUMBER(CONCAT(IPS.PRODUCT_GENERATED_IDENTIFIER, '00004')) = MR.PRODUCT_GENERATED_IDENTIFIER
AND TO_NUMBER(CONCAT('1040',IPS.LOCATION_GENERATED_IDENTIFIER,'00001')) = MR.LOCATION_GENERATED_IDENTIFIER
LEFT JOIN KSFPA.MR2C.KEYCODE KEY_CODE
ON MR.PRODUCT_GENERATED_IDENTIFIER = KEY_CODE.PRODUCT_GENERATED_IDENTIFIER
LEFT JOIN KSFPA.MR2C.LOCATION LOC
ON MR.LOCATION_GENERATED_IDENTIFIER = LOC.LOCATION_GENERATED_IDENTIFIER