WITH 

DCVAR_NEW AS 
(
SELECT
	-- LEVEL --
	RECON_WEEK_END_DATE AS WEEK_END_DATE ,
	
    ITEM_GENERATED_IDENTIFIER  		AS ITEM_ID,
    ORDER_GENERATED_IDENTIFIER 		AS ORDER_ID ,
	LOCATION_GENERATED_IDENTIFIER 	AS LOCATION_ID ,
	-- LEVEL --
	
	SUPPLIER_GENERATED_IDENTIFIER AS SUPPLIER_ID ,
    DC_CHARGE_RECONCILIATION_STATUS_CODE AS RECON_CODE ,
    
    OS_RECEIPT_COST_AMT 	AS RECEIPT_AMT ,
    OS_CHARGE_COST_AMT  	AS CHARGE_AMT ,
    OS_RECEIPT_VAR_COST_AMT AS VARIANCE_AMT ,

    OS_RECEIPT_QUANTITY 	AS RECEIPT_QTY ,
    OS_CHARGE_QTY 			AS CHARGE_QTY ,
    OS_RECEIPT_VAR_QUANTITY AS VARIANCE_QTY ,
    
    ROW_NUMBER() 
		OVER 
    		( 
			PARTITION BY ITEM_GENERATED_IDENTIFIER , ORDER_GENERATED_IDENTIFIER  
			ORDER BY RECON_WEEK_END_DATE DESC
			) 
		AS LATEST_WEEK_RANK
		
FROM KSFPA.MR2C.DC_CHARGE_RECONCILIATION 
)
,

DCVAR_OLD AS 
(
SELECT
    -- LEVEL --
    ITEM ,
    ORDER_NO ,
	RECON_WEEK ,
		-- LEVEL --
    RECONCILIATION_STATUS , RECONCILIATION_MESSAGE ,  -- RECON STATUS AND MSG ARE 1-1
    
    DC_RECEIPT_AMT AS RECEIPT_AMT ,
    DC_CHARGE_AMT AS CHARGE_AMT ,
    DC_RECEIPT_VAR_AMT AS VARIANCE_AMT ,

    DC_RECEIPT_QTY AS RECEIPT_QTY ,
    DC_CHARGE_QTY AS CHARGE_QTY ,
    DC_RECEIPT_VAR_QTY AS VARIANCE_QTY ,

    ORDER_STATUS  ,
    SUPPLIER ,
    VARIANCE_NOTE , -- 174 UNIQUE ,

    PERIOD ,
    ITEM_NAME ,
    SUPPLIER_NAME ,
    COUNTRY ,
    
    ROW_NUMBER() 
		OVER 
    		( 
			PARTITION BY ITEM , ORDER_NO 
			ORDER BY RECON_WEEK  desc
			) 
		AS RECON_WEEK_LATEST
		
FROM KSF_SOPHIA_DATA_INTELLIGENCE_HUB_DEV.SHRINK_TACTICAL.DC_CHARGE_VARIANCE
)


--SELECT * 
--FROM 
--    DCVAR_NEW N
--FULL OUTER JOIN
--    DCVAR_OLD O
--ON
--        O.ITEM      = N.ITEM_ID
--    AND O.ORDER_NO  = N.ORDER_ID
--    AND	O.RECON_WEEK= N.WEEK_END_DATE




SELECT LOCATION_ID , COunt(*)
FROM DCVAR_NEW N 
GROUP BY 1
;
