create or replace view KSF_DATAANALYTICS_DEV.DS_SHRINK_EXTERNAL.VW_EXT_FRAUD_INPUT(
	M_STORE,
    FREQ,
    DATED,
    AMOUNT
) as 
select 
	M_STORE,
    FREQ,
    DATED,
    AMT
from KSFDA.SHRINK_TACTICAL.EXTERNAL_FRAUD_INPUT_AMT;