--This Year NUmbers Code---
SELECT  DAY_FLAG, COUNT (DISTINCT MANIFEST_NO), COUNT (DISTINCT MANIFEST_NO, KEY_CODE), SUM(T_QTY)
FROM (
SELECT SR.STR_ID
        , SR.MANIFEST_NO
        , CAST(GETDATE() AS Date)
        , SR.SEAL_DATE
        , SR.RECEIPT_DATE
        , SR.DC_NUMBER
        , SM.KEY_CODE
        , SM.PRODUCT_DESCRIPTION
        , SM.DEPARTMENT
        , SUM(SM.TOTAL_QTY) AS T_QTY
        , CASE WHEN CAST(GETDATE() AS Date) - DATE(SR.SEAL_DATE) > 30 THEN 1
        WHEN CAST(GETDATE() AS Date) - DATE(SR.SEAL_DATE) <= 30 THEN 0 END AS DAY_FLAG
FROM KSFPA.WMS.STORE_MANIFESTS_RAW SM
INNER JOIN KSFPA.WMS.STORE_MANIFEST_RECEIPT_RAW SR
ON SM.MANIFEST_NO = SR.MANIFEST_NO
INNER JOIN KSFPA.MR2C."LOCATION" LOC
ON SM.STR_ID = LOC.LOCATION_SOURCE_IDENTIFIER
INNER JOIN KSFPA.LOSS_PREVENTION_PVT.DEPARTMENT_GM_APPAREL_CATEGORY APP_GM
ON APP_GM.DEPARTMENT_SOURCE_IDENTIFIER = DEPARTMENT
INNER JOIN KSFPA.MR2C.KEYCODE KC
ON SM.KEY_CODE = KC.PRODUCT_SOURCE_IDENTIFIER
INNER JOIN (SELECT PRODUCT_SOURCE_IDENTIFIER,
				   LOCATION_SOURCE_IDENTIFIER,
				   DAY_DATE,
				   DAILY_STOCK_ON_HAND_QUANTITY 
		   	FROM KSFPA.MR2C.DAILY_SOH DS
		   	INNER JOIN KSFPA.MR2C."LOCATION" LOC
			ON DS.LOCATION_GENERATED_IDENTIFIER = LOC.LOCATION_GENERATED_IDENTIFIER 
			INNER JOIN KSFPA.MR2C.KEYCODE KC
			ON DS.PRODUCT_GENERATED_IDENTIFIER = KC.PRODUCT_GENERATED_IDENTIFIER 
			WHERE DAY_DATE = '2022-11-24') SOH
ON SM.KEY_CODE = SOH.PRODUCT_SOURCE_IDENTIFIER AND SM.STR_ID = SOH.LOCATION_SOURCE_IDENTIFIER 
WHERE DATE(SR.SEAL_DATE) > '2022-02-20'
AND SR.RECEIPT_DATE IS NULL
AND SR.MANIFEST_TYPE = 'S'
AND DAILY_STOCK_ON_HAND_QUANTITY <0 -- Negative SOH Filter 
-- AND SR.DC_NUMBER = 9324 --Uncomment for Truganina numbers
GROUP BY 1,2,3,4,5,6,7,8,9)
GROUP BY 1

--Last Year Numbers Code---

SELECT  DAY_FLAG, COUNT (DISTINCT MANIFEST_NO), COUNT (DISTINCT MANIFEST_NO, KEY_CODE), SUM(T_QTY)
FROM (
SELECT SR.STR_ID
        , SR.MANIFEST_NO
        , SR.SEAL_DATE
        , SR.RECEIPT_DATE
        , SR.DC_NUMBER
        , SM.KEY_CODE
        , SM.PRODUCT_DESCRIPTION
        , SM.DEPARTMENT
        , SUM(SM.TOTAL_QTY) AS T_QTY
        , CASE WHEN DATE('2021-11-25') - DATE(SR.SEAL_DATE) > 30 THEN 1
        WHEN DATE('2021-11-25') - DATE(SR.SEAL_DATE) <= 30 THEN 0 END AS DAY_FLAG
FROM KSFPA.WMS.STORE_MANIFESTS_RAW SM
INNER JOIN KSFPA.WMS.STORE_MANIFEST_RECEIPT_RAW SR
ON SM.MANIFEST_NO = SR.MANIFEST_NO
INNER JOIN KSFPA.MR2C."LOCATION" LOC
ON SM.STR_ID = LOC.LOCATION_SOURCE_IDENTIFIER
INNER JOIN KSFPA.LOSS_PREVENTION_PVT.DEPARTMENT_GM_APPAREL_CATEGORY APP_GM
ON APP_GM.DEPARTMENT_SOURCE_IDENTIFIER = DEPARTMENT
INNER JOIN KSFPA.MR2C.KEYCODE KC
ON SM.KEY_CODE = KC.PRODUCT_SOURCE_IDENTIFIER
INNER JOIN (SELECT PRODUCT_SOURCE_IDENTIFIER,
				   LOCATION_SOURCE_IDENTIFIER,
				   DAY_DATE,
				   DAILY_STOCK_ON_HAND_QUANTITY 
		   	FROM KSFPA.MR2C.DAILY_SOH DS
		   	INNER JOIN KSFPA.MR2C."LOCATION" LOC
			ON DS.LOCATION_GENERATED_IDENTIFIER = LOC.LOCATION_GENERATED_IDENTIFIER 
			INNER JOIN KSFPA.MR2C.KEYCODE KC
			ON DS.PRODUCT_GENERATED_IDENTIFIER = KC.PRODUCT_GENERATED_IDENTIFIER 
			WHERE DAY_DATE = '2021-11-24') SOH
ON SM.KEY_CODE = SOH.PRODUCT_SOURCE_IDENTIFIER AND SM.STR_ID = SOH.LOCATION_SOURCE_IDENTIFIER 
WHERE DATE(SR.SEAL_DATE) BETWEEN DATE('2021-03-08') AND DATE('2021-11-24')
AND  (DATE(SR.RECEIPT_DATE) > DATE('2021-11-24') OR DATE(SR.RECEIPT_DATE) IS NULL)
AND SR.MANIFEST_TYPE = 'S'
--AND DAILY_STOCK_ON_HAND_QUANTITY <0
AND SR.DC_NUMBER = 9324
GROUP BY 1,2,3,4,5,6,7,8)
--WHERE DAY_FLAG = 1
GROUP BY 1


---Query to bring Dollar Value---

SELECT  DAY_FLAG,
		 COUNT (DISTINCT MANIFEST_NO)
		, COUNT (DISTINCT MANIFEST_NO, KEY_CODE)
		, SUM(T_QTY)
		, SUM(DOLLAR_VALUE)
FROM (
SELECT SR.STR_ID
        , SR.MANIFEST_NO
        , CAST(GETDATE() AS Date)
        , SR.SEAL_DATE
        , SR.RECEIPT_DATE
        , SR.DC_NUMBER
        , SM.KEY_CODE
        , SM.PRODUCT_DESCRIPTION
        , SM.DEPARTMENT
        , LOCATION_AWC_AMOUNT
        , SUM(SM.TOTAL_QTY) AS T_QTY
        , SUM(SM.TOTAL_QTY) * LOCATION_AWC_AMOUNT AS DOLLAR_VALUE
        , CASE WHEN DATE('2022-11-24') - DATE(SR.SEAL_DATE) > 30 THEN 1
        WHEN DATE('2022-11-24') - DATE(SR.SEAL_DATE) <= 30 THEN 0 END AS DAY_FLAG
FROM KSFPA.WMS.STORE_MANIFESTS_RAW SM
INNER JOIN KSFPA.WMS.STORE_MANIFEST_RECEIPT_RAW SR
ON SM.MANIFEST_NO = SR.MANIFEST_NO
INNER JOIN KSFPA.MR2C."LOCATION" LOC
ON SM.STR_ID = LOC.LOCATION_SOURCE_IDENTIFIER
INNER JOIN KSFPA.LOSS_PREVENTION_PVT.DEPARTMENT_GM_APPAREL_CATEGORY APP_GM
ON APP_GM.DEPARTMENT_SOURCE_IDENTIFIER = DEPARTMENT
INNER JOIN KSFPA.MR2C.KEYCODE KC
ON SM.KEY_CODE = KC.PRODUCT_SOURCE_IDENTIFIER
INNER JOIN (SELECT PRODUCT_SOURCE_IDENTIFIER,
				   LOCATION_SOURCE_IDENTIFIER,
				   DAY_DATE,
				   DAILY_STOCK_ON_HAND_QUANTITY 
		   	FROM KSFPA.MR2C.DAILY_SOH DS
		   	INNER JOIN KSFPA.MR2C."LOCATION" LOC
			ON DS.LOCATION_GENERATED_IDENTIFIER = LOC.LOCATION_GENERATED_IDENTIFIER 
			INNER JOIN KSFPA.MR2C.KEYCODE KC
			ON DS.PRODUCT_GENERATED_IDENTIFIER = KC.PRODUCT_GENERATED_IDENTIFIER 
			WHERE DAY_DATE = '2022-11-24') SOH
ON SM.KEY_CODE = SOH.PRODUCT_SOURCE_IDENTIFIER AND SM.STR_ID = SOH.LOCATION_SOURCE_IDENTIFIER 
INNER JOIN (SELECT PRODUCT_SOURCE_IDENTIFIER  
					, LOCATION_SOURCE_IDENTIFIER  
					, EFFECTIVE_DATE
					, LOCATION_AWC_AMOUNT
			FROM KSFPA.MR2.SS_AVERAGE_WEIGHTED_COST WC
			INNER JOIN KSFPA.MR2C."LOCATION" LOC
			ON WC.LOCATION_GENERATED_IDENTIFIER = LOC.LOCATION_GENERATED_IDENTIFIER 
			INNER JOIN KSFPA.MR2C.KEYCODE KC
			ON WC.PRODUCT_GENERATED_IDENTIFIER = KC.PRODUCT_GENERATED_IDENTIFIER 
			WHERE EXPIRY_DATE = '9999-12-31') DV
ON DV.LOCATION_SOURCE_IDENTIFIER  = SM.STR_ID AND DV.PRODUCT_SOURCE_IDENTIFIER = SM.KEY_CODE 
WHERE DATE(SR.SEAL_DATE) > '2022-02-20'
AND SR.RECEIPT_DATE IS NULL
AND SR.MANIFEST_TYPE = 'S'
AND DAILY_STOCK_ON_HAND_QUANTITY <0
GROUP BY 1,2,3,4,5,6,7,8,9,10)
--WHERE DAY_FLAG = 1
GROUP BY 1
