SELECT  DAY_FLAG
		, COUNT (DISTINCT TRANSFER_GENERATED_IDENTIFIER)
		, COUNT (DISTINCT TRANSFER_GENERATED_IDENTIFIER, PRODUCT_GENERATED_IDENTIFIER)
		, SUM(T_QTY)
		, SUM(DOLLAR_VALUE)
		, SUM(DAILY_STOCK_ON_HAND_QUANTITY)
		, SUM(NSOH_VALUE) 
FROM 
	(
		SELECT TRANSFER_GENERATED_IDENTIFIER
				, MNFST.STR_ID
				, MNFST.DC_NUMBER
				, MNFST.TRANSFER_SOURCE_IDENTIFIER 
				, MNFST.PRODUCT_GENERATED_IDENTIFIER 
		        , CAST(GETDATE() AS Date)
		        , MNFST.DESPATCH_DATE 
		        , RECEIPT_DATE 
		        , WMS_MANIFEST_TYPE_CODE 
		        , T_QTY
		        , DAILY_STOCK_ON_HAND_QUANTITY AS DAILY_STOCK_ON_HAND_QUANTITY
		        , DAILY_STOCK_ON_HAND_QUANTITY * LOCATION_AWC_AMOUNT AS NSOH_VALUE
		        , T_QTY * LOCATION_AWC_AMOUNT AS DOLLAR_VALUE
		        , CASE WHEN DATE('2023-01-04') - DATE(MNFST.DESPATCH_DATE) > 30 THEN 1
		        WHEN DATE('2023-01-04') - DATE(MNFST.DESPATCH_DATE) <= 30 THEN 0 END AS DAY_FLAG		
			FROM (SELECT TD.TRANSFER_GENERATED_IDENTIFIER 
						, TP.PRODUCT_GENERATED_IDENTIFIER 
						, TD.LOCATION_GENERATED_IDENTIFIER AS DC_NUMBER 
						, TR.LOCATION_GENERATED_IDENTIFIER AS STR_ID
						, TD.TRANSFER_SOURCE_IDENTIFIER 
						, TD.DESPATCH_DATE 
						, TD.EXPIRY_DATE 
						, RECEIPT_DATE
						, SUM(TP.DESPATCH_QUANTITY) AS T_QTY
				FROM KSFPA.MR2.TRANSFER_DESPATCH TD
				LEFT JOIN KSFPA.MR2.TRANSFER_RECEIPT TR
				ON TD.TRANSFER_GENERATED_IDENTIFIER = TR.TRANSFER_GENERATED_IDENTIFIER 
				INNER JOIN KSFPA.MR2.TRANSFER_PRODUCT TP
				ON TD.TRANSFER_GENERATED_IDENTIFIER = TP.TRANSFER_GENERATED_IDENTIFIER AND TD.EXPIRY_DATE = TP.EXPIRY_DATE 
				WHERE TR.RECEIPT_DATE  IS NULL
				AND TD.DESPATCH_DATE > '2022-02-20'
				AND TD.EXPIRY_DATE  = '9999-12-31'
				AND TR.EXPIRY_DATE = '9999-12-31'
				AND TD.TRANSFER_TYPE_CODE = 'DD'
				GROUP BY 1,2,3,4,5,6,7,8
			) MNFST
		INNER JOIN (SELECT DISTINCT TRANSFER_SOURCE_IDENTIFIER
									, WMS_MANIFEST_TYPE_CODE 
					FROM KSFPA.MR2.WMS_MANIFEST
					WHERE WMS_MANIFEST_TYPE_CODE = 'S'
					AND DAY_DATE > '2022-02-20') WM
		ON WM.TRANSFER_SOURCE_IDENTIFIER = MNFST.TRANSFER_SOURCE_IDENTIFIER
		INNER JOIN (SELECT 
						   DAY_DATE,
						   DAILY_STOCK_ON_HAND_QUANTITY,
						   DS.PRODUCT_GENERATED_IDENTIFIER,
						   DS.LOCATION_GENERATED_IDENTIFIER 
				   	FROM KSFPA.MR2C.DAILY_SOH DS
				   	INNER JOIN KSFPA.MR2C."LOCATION" LOC
					ON DS.LOCATION_GENERATED_IDENTIFIER = LOC.LOCATION_GENERATED_IDENTIFIER 
					INNER JOIN KSFPA.MR2C.KEYCODE KC
					ON DS.PRODUCT_GENERATED_IDENTIFIER = KC.PRODUCT_GENERATED_IDENTIFIER 
					WHERE DAY_DATE = '2023-01-04') SOH
		ON MNFST.PRODUCT_GENERATED_IDENTIFIER  = SOH.PRODUCT_GENERATED_IDENTIFIER  AND MNFST.STR_ID  = SOH.LOCATION_GENERATED_IDENTIFIER  
		INNER JOIN (SELECT WC.PRODUCT_GENERATED_IDENTIFIER 
							, WC.LOCATION_GENERATED_IDENTIFIER  
							, EFFECTIVE_DATE
							, LOCATION_AWC_AMOUNT
					FROM KSFPA.MR2.SS_AVERAGE_WEIGHTED_COST WC
					WHERE EXPIRY_DATE = '9999-12-31') DV
		ON DV.LOCATION_GENERATED_IDENTIFIER = MNFST.STR_ID  AND DV.PRODUCT_GENERATED_IDENTIFIER  = MNFST.PRODUCT_GENERATED_IDENTIFIER  
		WHERE DAILY_STOCK_ON_HAND_QUANTITY <0
		ORDER BY 1,2,3)
GROUP BY 1

-----LY Numbers-----
SELECT  DAY_FLAG
		, COUNT (DISTINCT TRANSFER_GENERATED_IDENTIFIER)
		, COUNT (DISTINCT TRANSFER_GENERATED_IDENTIFIER, PRODUCT_GENERATED_IDENTIFIER)
		, SUM(T_QTY)
		, SUM(DOLLAR_VALUE)
		, SUM(DAILY_STOCK_ON_HAND_QUANTITY)
		, SUM(NSOH_VALUE) 
FROM 
	(
		SELECT TRANSFER_GENERATED_IDENTIFIER
				, MNFST.STR_ID
				, MNFST.DC_NUMBER
				, MNFST.TRANSFER_SOURCE_IDENTIFIER 
				, MNFST.PRODUCT_GENERATED_IDENTIFIER 
		        , CAST(GETDATE() AS Date)
		        , MNFST.DESPATCH_DATE 
		        , RECEIPT_DATE 
		        , WMS_MANIFEST_TYPE_CODE 
		        , T_QTY
		        , DAILY_STOCK_ON_HAND_QUANTITY AS DAILY_STOCK_ON_HAND_QUANTITY
		        , DAILY_STOCK_ON_HAND_QUANTITY * LOCATION_AWC_AMOUNT AS NSOH_VALUE
		        , T_QTY * LOCATION_AWC_AMOUNT AS DOLLAR_VALUE
		        , CASE WHEN DATE('2022-01-04') - DATE(MNFST.DESPATCH_DATE) > 30 THEN 1
		        WHEN DATE('2022-01-04') - DATE(MNFST.DESPATCH_DATE) <= 30 THEN 0 END AS DAY_FLAG		
			FROM (SELECT TD.TRANSFER_GENERATED_IDENTIFIER 
						, TP.PRODUCT_GENERATED_IDENTIFIER 
						, TD.LOCATION_GENERATED_IDENTIFIER AS DC_NUMBER 
						, TR.LOCATION_GENERATED_IDENTIFIER AS STR_ID
						, TD.TRANSFER_SOURCE_IDENTIFIER 
						, TD.DESPATCH_DATE 
						, TD.EXPIRY_DATE 
						, RECEIPT_DATE
						, SUM(TP.DESPATCH_QUANTITY) AS T_QTY
				FROM KSFPA.MR2.TRANSFER_DESPATCH TD
				LEFT JOIN KSFPA.MR2.TRANSFER_RECEIPT TR
				ON TD.TRANSFER_GENERATED_IDENTIFIER = TR.TRANSFER_GENERATED_IDENTIFIER 
				INNER JOIN KSFPA.MR2.TRANSFER_PRODUCT TP
				ON TD.TRANSFER_GENERATED_IDENTIFIER = TP.TRANSFER_GENERATED_IDENTIFIER AND TD.EXPIRY_DATE = TP.EXPIRY_DATE 
				WHERE (TR.RECEIPT_DATE  IS NULL OR TR.RECEIPT_DATE > DATE('2022-01-04'))
				AND TD.DESPATCH_DATE > '2021-03-07'
				AND TD.EXPIRY_DATE  = '9999-12-31'
--				AND TP.EXPIRY_DATE = '999-12-31'
				AND TR.EXPIRY_DATE = '9999-12-31'
				AND TD.TRANSFER_TYPE_CODE = 'DD'
				GROUP BY 1,2,3,4,5,6,7,8
			) MNFST
		INNER JOIN (SELECT DISTINCT TRANSFER_SOURCE_IDENTIFIER
									, WMS_MANIFEST_TYPE_CODE 
					FROM KSFPA.MR2.WMS_MANIFEST
					WHERE WMS_MANIFEST_TYPE_CODE = 'S'
					AND DAY_DATE BETWEEN DATE('2021-03-08') AND DATE('2022-01-04')) WM
		ON WM.TRANSFER_SOURCE_IDENTIFIER = MNFST.TRANSFER_SOURCE_IDENTIFIER
		INNER JOIN (SELECT 
						   DAY_DATE,
						   DAILY_STOCK_ON_HAND_QUANTITY,
						   DS.PRODUCT_GENERATED_IDENTIFIER,
						   DS.LOCATION_GENERATED_IDENTIFIER 
				   	FROM KSFPA.MR2C.DAILY_SOH DS
				   	INNER JOIN KSFPA.MR2C."LOCATION" LOC
					ON DS.LOCATION_GENERATED_IDENTIFIER = LOC.LOCATION_GENERATED_IDENTIFIER 
					INNER JOIN KSFPA.MR2C.KEYCODE KC
					ON DS.PRODUCT_GENERATED_IDENTIFIER = KC.PRODUCT_GENERATED_IDENTIFIER 
					WHERE DAY_DATE = '2022-01-04') SOH
		ON MNFST.PRODUCT_GENERATED_IDENTIFIER  = SOH.PRODUCT_GENERATED_IDENTIFIER  AND MNFST.STR_ID  = SOH.LOCATION_GENERATED_IDENTIFIER  
		INNER JOIN (SELECT WC.PRODUCT_GENERATED_IDENTIFIER 
							, WC.LOCATION_GENERATED_IDENTIFIER  
							, EFFECTIVE_DATE
							, LOCATION_AWC_AMOUNT
					FROM KSFPA.MR2.SS_AVERAGE_WEIGHTED_COST WC
					WHERE EXPIRY_DATE = '9999-12-31') DV
		ON DV.LOCATION_GENERATED_IDENTIFIER = MNFST.STR_ID  AND DV.PRODUCT_GENERATED_IDENTIFIER  = MNFST.PRODUCT_GENERATED_IDENTIFIER  
--		WHERE DAILY_STOCK_ON_HAND_QUANTITY <0
		ORDER BY 1,2,3)
GROUP BY 1